import {Prism} from 'prism-react-renderer';

const accessModifiers = [
  'public',
  'private',
  'protected',
  'static',
  'final',
  'super',
  'synchronized',
  'bridge',
  'varargs',
  'native',
  'abstract',
  'strictfp',
  'volatile',
  'transient',
  'synthetic',
  'annotation',
  'enum',
].join('|');

const instructions = [
  'aaload',
  'aastore',
  'aconst_null',
  'aload',
  'aload_[0-4]',
  'anewarray',
  'areturn',
  'arraylength',
  'astore',
  'astore_[0-3]',
  'athrow',
  'baload',
  'bastore',
  'bipush',
  'caload',
  'castore',
  'checkcast',
  'd2[fil]',
  'dadd',
  'daload',
  'dastore',
  'dcmp[gl]',
  'dconst_[01]',
  'ddiv',
  'dload',
  'dload_[0-3]',
  'dmul',
  'dneg',
  'drem',
  'dreturn',
  'dstore',
  'dstore_[0-3]',
  'dsub',
  'dup(?:2(?:_x[12])?|_x[12])?',
  'f2[dil]',
  'fadd',
  'faload',
  'fastore',
  'fcmp[gl]',
  'fconst_[0-2]',
  'fdiv',
  'fload',
  'fload_[0-3]',
  'fmul',
  'fneg',
  'frem',
  'freturn',
  'fstore',
  'fstore_[0-3]',
  'fsub',
  'getfield',
  'getstatic',
  'goto(?:_w)?',
  'i2[bcdfils]',
  'iadd',
  'iaload',
  'iand',
  'iastore',
  'iconst_(?:m1|[0-5])',
  'idiv',
  'if(?:_acmp(?:eq|ne)|_icmp(?:eq|ne|lt|ge|gt|le)|eq|ne|lt|ge|gt|le|nonnull|null)',
  'iinc',
  'iload',
  'iload_[0-3]',
  'imul',
  'ineg',
  'instanceof',
  'invokedynamic',
  'invokeinterface',
  'invokespecial',
  'invokestatic',
  'invokevirtual',
  'ior',
  'irem',
  'ireturn',
  'ishl',
  'ishr',
  'istore',
  'istore_[0-3]',
  'isub',
  'iushr',
  'ixor',
  'jsr(?:_w)?',
  'l2[dfi]',
  'ladd',
  'laload',
  'land',
  'lastore',
  'lcmp',
  'lconst_[01]',
  'ldc(?:2?_w)?',
  'ldiv',
  'lload',
  'lload_[0-3]',
  'lmul',
  'lneg',
  'lookupswitch',
  'lor',
  'lrem',
  'lreturn',
  'lshl',
  'lshr',
  'lstore',
  'lstore_[0-3]',
  'lsub',
  'lushr',
  'lxor',
  'monitorenter',
  'monitorexit',
  'multianewarray',
  'new',
  'newarray',
  'nop',
  'pop2?',
  'putfield',
  'putstatic',
  'ret',
  'return',
  'saload',
  'sastore',
  'sipush',
  'swap',
  'tableswitch',
  'wide',
].join('|');

const word = (value: string): RegExp => new RegExp(`\\b(?:${value})\\b`);

Prism.languages.jal = {
  comment: [
    {
      pattern: /(^|[^\\])\/\*[\s\S]*?\*\//,
      lookbehind: true,
      greedy: true,
    },
    {
      pattern: /(^|[^\\:])\/\/.*/,
      lookbehind: true,
      greedy: true,
    },
  ],
  string: {
    pattern: /"(?:\\[\s\S]|[^"\\])*"/,
    greedy: true,
  },
  'local-declaration': {
    pattern: /\[(?:\[*L[^;\s()[\]{},:]+;|\[*[BCDFIJSVZ])?(?:\s*~\s*[a-zA-Z$_][\w$]*)?\s*->\s*[a-zA-Z$_][\w$]*\]/,
    inside: {
      operator: /->|~/,
      punctuation: /[\[\]]/,
      'type-descriptor': {
        pattern: /\[*L[^;\s()[\]{},:]+;|\[*[BCDFIJSVZ]\b/,
        alias: 'class-name',
      },
      variable: /[a-zA-Z$_][\w$]*/,
    },
  },
  'method-reference': {
    pattern: /\b[a-zA-Z$_][\w$]*(?:\/[a-zA-Z$_][\w$]*)*->[a-zA-Z$_][\w$]*(?=\()/,
    inside: {
      'class-name': /^[a-zA-Z$_][\w$]*(?:\/[a-zA-Z$_][\w$]*)*/,
      function: /[a-zA-Z$_][\w$]*$/,
      operator: /->/,
      punctuation: /\//,
    },
  },
  'method-descriptor': {
    pattern: /\((?:\[*[BCDFIJSVZ]|\[*L[a-zA-Z0-9_/$]+;)*\)\[*[BCDFIJSVZ]|\((?:\[*[BCDFIJSVZ]|\[*L[a-zA-Z0-9_/$]+;)*\)\[*L[a-zA-Z0-9_/$]+;/,
    alias: 'class-name',
  },
  'type-descriptor': {
    pattern: /\[*L[^;\s()[\]{},:]+;|\[*[BCDFIJSVZ]\b/,
    alias: 'class-name',
  },
  'field-reference': {
    pattern: /\b[a-zA-Z$_][\w$]*(?:\/[a-zA-Z$_][\w$]*)*->[a-zA-Z$_][\w$]*:/,
    inside: {
      'class-name': /^[a-zA-Z$_][\w$]*(?:\/[a-zA-Z$_][\w$]*)*/,
      property: /[a-zA-Z$_][\w$]*(?=:)/,
      operator: /->/,
      punctuation: /[:/]/,
    },
  },
  label: {
    pattern: /^\s*[a-zA-Z$_][\w$]*(?=:)/m,
    alias: 'symbol',
  },
  keyword: word(
    `class|interface|default|major_version|minor_version|super_class|interfaces|MethodType\\||MethodHandle\\||newinvokespecial|<init>|<clinit>|${accessModifiers}`,
  ),
  instruction: {
    pattern: word(instructions),
    alias: 'builtin',
  },
  boolean: word('true|false'),
  number: /-?(?:0x[\da-fA-F]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)[fFdDlL]?/,
  operator: /->|[=~|]/,
  punctuation: /[{}()[\],:;.]/,
};

Prism.languages.jasm = Prism.languages.jal;
